#!/usr/bin/env php
<?php

declare(strict_types=1);

use Tamiroh\GameOfLife\CellState;

require __DIR__ . '/vendor/autoload.php';

$gameOfLife = new \Tamiroh\GameOfLife\GameOfLife([
    [1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0],
    [0, 0, 1, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 1, 0, 1, 0, 0, 0],
]);

while (true) {
    $gameOfLife->next();

    ob_start();
        foreach ($gameOfLife->state as $columns) {
            foreach ($columns as $cell) {
                echo $cell === CellState::Alive ? '🟥 ' : '⬜️ ';
            }
            echo PHP_EOL;
        }
        echo ob_get_clean();
    echo '-----------' . PHP_EOL;

    usleep(200000);
}